[workspace]
members = [".", "w3c-validation"]
resolver = "2"

[package]
name = "de"
version = "0.2.0"
authors = ["bharath181 <bharathselvaraj18@gmail.com>", "Greg Hanson <g.isaac.hanson@gmail.com>", "Donald Anthony Pellegrino Jr., Ph.D. <don@decisym.ai>"]
edition = "2024"
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/DeciSym/de"
default-run = "de"
keywords = ["hdt", "rdf", "semantic-web", "triple-store", "sparql"]
categories = ["command-line-utilities"]

[[bin]]
name = "de"
path = "src/main.rs"
bench = false

[[bench]]
name = "benchmark"
harness = false

[dependencies]
anyhow = { version = "1.0", default-features = false }
async-trait = "0.1"
bzip2 = "0.6"
clap = { version = "4.5" }
clap-verbosity-flag = { version = "3.0", default-features = false, features = ["log"] }
env_logger = { version = "0.11", default-features = false }
exitcode = "1.1"
flate2 = "1"
hdt = { version = "0.7.3", default-features = false, features = ["nt", "cache"] }
http = { version = "1.4", optional = true }
log = "0.4"
oxhttp = { version = "0.3", optional=true }
oxrdf = "0.3"
oxrdfio = "0.2"
rayon = "1.11.0"
sparesults = "0.3"
spareval = { version = "0.2", features = ["sep-0002", "sep-0006"] }
spargebra = "0.4"
reasonable = "0.4.3"
tempfile = {version = "3.27"}
thiserror = "2.0"
tokio = { version = "1.49", default-features = false, features = ["full"] }
url = { version = "2.5" }

[dev-dependencies]
urlencoding = "2.1"
criterion = { version = "0.5", features = ["async_tokio"] }
futures = "0.3"
w3c-validation = { path = "w3c-validation" }

[target.'cfg(target_os = "linux")'.dev-dependencies]
pprof = { version = "0.15", features = ["protobuf", "protobuf-codec", "criterion"] }

[package.metadata.deb]
maintainer = "DeciSym.AI <support@decisym.ai>"
copyright = "2023, DeciSym.AI."
extended-description = "CLI tool for creating and querying hdt files"
section = "utils"
priority = "optional"
assets = [
    # binary
    ["target/release/de", "usr/bin/", "755"], 

]
default-features = false

[features]
default = []
server = ["dep:oxhttp", "dep:http"]

[patch.crates-io]
spareval = { git = "https://github.com/DeciSym/oxigraph.git", rev = "ed7335a2bc224c4fd71b7e6dfe7ce93a96485115" }
sparopt = { git = "https://github.com/DeciSym/oxigraph.git", rev = "ed7335a2bc224c4fd71b7e6dfe7ce93a96485115" }
spargebra = { git = "https://github.com/DeciSym/oxigraph.git", rev = "ed7335a2bc224c4fd71b7e6dfe7ce93a96485115" }
sparesults = { git = "https://github.com/DeciSym/oxigraph.git", rev = "ed7335a2bc224c4fd71b7e6dfe7ce93a96485115" }
oxrdfxml = { git = "https://github.com/DeciSym/oxigraph.git", rev = "ed7335a2bc224c4fd71b7e6dfe7ce93a96485115" }
reasonable = { git = "https://github.com/DeciSym/reasonable.git", rev = "c961cfc1c45a09b218d8910c387b8c5c4ef3df03" }
hdt = { git = "https://github.com/DeciSym/hdt.git", rev = "919c725fd5f0e42662f9e3824e3f96d86baa8bb4" }

